#!/usr/bin/env bash
# Goldy — Generate TRUTH.md (master source of truth) from all project data
# Usage: generate-truth.sh

set -euo pipefail

WORKSPACE="$(cd "$(dirname "$0")/.." && pwd)"
CHANGELOG_BASE="$WORKSPACE/memory/changelogs"
SUMMARY_DIR="$WORKSPACE/memory/summaries"
OUTFILE="$WORKSPACE/TRUTH.md"
PROJECTS=("vance-ios" "vance-android")
TODAY=$(date '+%Y-%m-%d')

cat > "$OUTFILE" <<EOF
# TRUTH.md — Cross-Project State

> Auto-generated by Goldy on $TODAY. Do not edit manually.

## Platform Status

| Project | Branch | Last Commit | Last Date | Changelogs |
|---------|--------|-------------|-----------|------------|
EOF

# Platform status table
for project in "${PROJECTS[@]}"; do
  repo_dir="$WORKSPACE/$project"
  changelog_dir="$CHANGELOG_BASE/$project"

  branch="N/A"
  last_commit="N/A"
  last_date="N/A"
  count=0

  if [ -d "$repo_dir/.git" ]; then
    branch=$(cd "$repo_dir" && git branch --show-current 2>/dev/null || echo "detached")
    last_commit=$(cd "$repo_dir" && git log -1 --format='%h %s' 2>/dev/null || echo "N/A")
    last_date=$(cd "$repo_dir" && git log -1 --date=short --format='%cd' 2>/dev/null || echo "N/A")
  fi

  if [ -d "$changelog_dir" ]; then
    count=$(find "$changelog_dir" -name '*.md' 2>/dev/null | wc -l | tr -d ' ')
  fi

  echo "| $project | \`$branch\` | $last_commit | $last_date | $count |" >> "$OUTFILE"
done

# Cross-platform alerts
cat >> "$OUTFILE" <<EOF

## Cross-Platform Alerts

Commits touching shared contracts (API, schema, migration, shared):

EOF

alert_found=0
for project in "${PROJECTS[@]}"; do
  repo_dir="$WORKSPACE/$project"
  if [ -d "$repo_dir/.git" ]; then
    alerts=$(cd "$repo_dir" && git log --oneline -20 --grep="api\|schema\|migration\|shared\|contract\|endpoint\|payment" -i 2>/dev/null || echo "")
    if [ -n "$alerts" ]; then
      echo "### $project" >> "$OUTFILE"
      echo '```' >> "$OUTFILE"
      echo "$alerts" >> "$OUTFILE"
      echo '```' >> "$OUTFILE"
      echo "" >> "$OUTFILE"
      alert_found=1
    fi
  fi
done

if [ "$alert_found" -eq 0 ]; then
  echo "_No cross-platform alerts detected._" >> "$OUTFILE"
  echo "" >> "$OUTFILE"
fi

# Recent activity (7 days)
cat >> "$OUTFILE" <<EOF

## Recent Activity (7 days)

EOF

for project in "${PROJECTS[@]}"; do
  repo_dir="$WORKSPACE/$project"
  if [ -d "$repo_dir/.git" ]; then
    recent=$(cd "$repo_dir" && git log --oneline --since="7 days ago" 2>/dev/null || echo "")
    commit_count=$(echo "$recent" | grep -c . 2>/dev/null || echo "0")
    echo "### $project ($commit_count commits)" >> "$OUTFILE"
    if [ -n "$recent" ]; then
      echo '```' >> "$OUTFILE"
      echo "$recent" >> "$OUTFILE"
      echo '```' >> "$OUTFILE"
    else
      echo "_No commits in last 7 days._" >> "$OUTFILE"
    fi
    echo "" >> "$OUTFILE"
  fi
done

# Per-platform summaries (embed if they exist)
cat >> "$OUTFILE" <<EOF

## Per-Platform Summaries

EOF

for project in "${PROJECTS[@]}"; do
  summary_file="$SUMMARY_DIR/$project.md"
  if [ -f "$summary_file" ]; then
    echo "### $project" >> "$OUTFILE"
    echo "" >> "$OUTFILE"
    # Embed summary content (skip the first heading to avoid duplication)
    tail -n +3 "$summary_file" >> "$OUTFILE"
    echo "" >> "$OUTFILE"
    echo "---" >> "$OUTFILE"
    echo "" >> "$OUTFILE"
  fi
done

echo "Goldy: generated TRUTH.md → $OUTFILE"
