#!/usr/bin/env bash
# Goldy — Generate status report from git history + memory
# Usage: ./scripts/generate-report.sh [--hours 24] [--output slack|markdown|terminal]
#
# Reads git logs, changelogs, summaries, and memory to produce
# a structured team status report. Can output to terminal, markdown file,
# or formatted for Slack posting.

set -euo pipefail

WORKSPACE="$(cd "$(dirname "$0")/.." && pwd)"
HOURS=24
OUTPUT="terminal"
REPORT_DIR="$WORKSPACE/memory/reports"

# Parse args
while [[ $# -gt 0 ]]; do
  case $1 in
    --hours) HOURS="$2"; shift 2 ;;
    --output) OUTPUT="$2"; shift 2 ;;
    *) echo "Unknown arg: $1"; exit 1 ;;
  esac
done

# Auto-detect projects
source "$WORKSPACE/scripts/detect-projects.sh"

if [ ${#GOLDY_PROJECTS[@]} -eq 0 ]; then
  echo "No projects detected. Nothing to report."
  exit 1
fi

TODAY=$(date '+%Y-%m-%d')
NOW=$(date '+%H:%M')
SINCE="${HOURS} hours ago"

mkdir -p "$REPORT_DIR"

# ──────────────────────────────────────────────────────────────
# Collect data
# ──────────────────────────────────────────────────────────────

REPORT=""

# Header
REPORT+="**Status Report — ${TODAY} ${NOW}**"$'\n'
REPORT+=""$'\n'

# Per-project: branch, recent commits, stats
for project in "${GOLDY_PROJECTS[@]}"; do
  repo_dir="$WORKSPACE/$project"
  [ -d "$repo_dir/.git" ] || continue

  branch=$(cd "$repo_dir" && git branch --show-current 2>/dev/null || echo "detached")
  commit_count=$(cd "$repo_dir" && git log --oneline --since="$SINCE" 2>/dev/null | wc -l | tr -d ' ')
  last_commit=$(cd "$repo_dir" && git log -1 --format='%h %s' 2>/dev/null || echo "N/A")

  REPORT+="**${project}** (\`${branch}\`) — ${commit_count} commits in last ${HOURS}h"$'\n'

  if [ "$commit_count" -gt 0 ]; then
    # List commits
    while IFS= read -r line; do
      REPORT+="  - ${line}"$'\n'
    done < <(cd "$repo_dir" && git log --oneline --since="$SINCE" 2>/dev/null | head -15)
  else
    REPORT+="  - No commits in last ${HOURS}h (last: ${last_commit})"$'\n'
  fi

  # Files changed
  if [ "$commit_count" -gt 0 ]; then
    files_changed=$(cd "$repo_dir" && git diff --stat "HEAD~${commit_count}" HEAD 2>/dev/null | tail -1 | tr -d ' ' || echo "")
    if [ -n "$files_changed" ]; then
      REPORT+="  - Stats: ${files_changed}"$'\n'
    fi
  fi

  REPORT+=""$'\n'
done

# Cross-platform alerts (from TRUTH.md if available)
if [ -f "$WORKSPACE/TRUTH.md" ]; then
  alerts=$(grep -A 20 "Cross-Platform Alerts" "$WORKSPACE/TRUTH.md" 2>/dev/null | grep -v "^#" | grep -v "^$" | grep -v "^\`\`\`" | grep -v "^_No" | head -5 || echo "")
  if [ -n "$alerts" ]; then
    REPORT+="**Cross-Platform Alerts**"$'\n'
    while IFS= read -r line; do
      [ -n "$line" ] && REPORT+="  - ${line}"$'\n'
    done <<< "$alerts"
    REPORT+=""$'\n'
  fi
fi

# Changelog summary (recent)
total_changelogs=0
for project in "${GOLDY_PROJECTS[@]}"; do
  changelog_dir="$WORKSPACE/memory/changelogs/$project"
  if [ -d "$changelog_dir" ]; then
    recent=$(find "$changelog_dir" -name "${TODAY}*.md" 2>/dev/null | wc -l | tr -d ' ')
    total_changelogs=$((total_changelogs + recent))
  fi
done
REPORT+="**Infrastructure**: ${total_changelogs} changelogs generated today"$'\n'

# Review bot status (if learnings exist)
learnings_dir="$WORKSPACE/claude-review-bot/.github/actions/claude-review/learnings"
if [ -d "$learnings_dir" ]; then
  reviewer_count=$(find "$learnings_dir" -name '*.json' 2>/dev/null | wc -l | tr -d ' ')
  total_patterns=0
  for f in "$learnings_dir"/*.json; do
    [ -f "$f" ] || continue
    p=$(grep -c '"id"' "$f" 2>/dev/null || echo "0")
    total_patterns=$((total_patterns + p))
  done
  REPORT+="**Review Bot**: ${reviewer_count} reviewers, ${total_patterns} patterns enforced"$'\n'
fi

REPORT+=""$'\n'
REPORT+="---"$'\n'
REPORT+="_Generated by Goldy_"$'\n'

# ──────────────────────────────────────────────────────────────
# Output
# ──────────────────────────────────────────────────────────────

case "$OUTPUT" in
  terminal)
    echo "$REPORT"
    ;;
  markdown)
    outfile="$REPORT_DIR/report_${TODAY}.md"
    echo "$REPORT" > "$outfile"
    echo "Goldy: report saved to $outfile"
    ;;
  slack)
    # Output Slack-formatted (mrkdwn) — ready to pipe into Slack API
    # Convert **bold** to *bold* (Slack uses single asterisk)
    slack_report=$(echo "$REPORT" | sed 's/\*\*\([^*]*\)\*\*/\*\1\*/g')
    echo "$slack_report"
    ;;
  *)
    echo "Unknown output format: $OUTPUT (use: terminal, markdown, slack)"
    exit 1
    ;;
esac
